name: tis_script
description: A visual node based programming language for Dart User.

version: 2.5.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  bot_toast: ^2.4.0
  font_awesome_flutter: ^8.8.1
  recase: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
